src/main/java/br/com/tkd/spartanos/model/Connection.java
package br.com.tkd.spartanos.model;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

public final class Connection {
    private static EntityManagerFactory factory = Persistence.createEntityManagerFactory("fatec");

    public static EntityManager getEntityManager() {
        return factory.createEntityManager();
    }
}

src/main/java/br/com/tkd/spartanos/model/constants/Gender.java
package br.com.tkd.spartanos.model.constants;

import lombok.Getter;

public enum Gender {
    FEMALE("Feminino"),
    MALE("Masculino");

    @Getter
    private String description;

    Gender(String description) {
       this.description = description;
    }
}

src/main/java/br/com/tkd/spartanos/model/constants/Graduation.java
package br.com.tkd.spartanos.model.constants;

import lombok.Getter;

public enum Graduation {
    WHITE("Branca"),
    YELLOW("Amarela"),
    YELLOW_GREEN("Amarela ponta Verde"),
    GREEN("Verde"),
    GREEN_BLUE("Verde ponta aAul"),
    BLUE("Azul"),
    BLUE_RED("Azul ponta Vermelha"),
    RED("Vermelha"),
    RED_BLACK("Vermelha ponta Preta"),
    BLACK("Preta");

    @Getter
    private String description;

    Graduation(String description) {
       this.description = description;
    }
}

src/main/java/br/com/tkd/spartanos/model/constants/Month.java
package br.com.tkd.spartanos.model.constants;

import lombok.Getter;

public enum Month {
    JANEIRO(1, "Janeiro"),
    FEVEIRO(2, "Fevereiro"),
    MARCO(3, "Março"),
    ABRIL(4, "Abril"),
    MAIO(5, "Maio"),
    JUNHO(6, "Junho"),
    JULHO(7, "Julho"),
    AGOSTO(8, "Agosot"),
    SETEMBRO(9, "Setembro"),
    OUTUBRO(10, "Novembro"),
    NOVEMBRo(11, "Dezembro"),
    DEZEMBRO(12, "Janeiro");

    @Getter
    private Integer value;

    @Getter
    private String description;

    Month(Integer value, String description) {
       this.value = value;
       this.description = description;
    }
}

src/main/java/br/com/tkd/spartanos/model/dao/AthleteDAO.java
package br.com.tkd.spartanos.model.dao;

import java.time.LocalDateTime;
import java.util.List;

import br.com.tkd.spartanos.model.entity.Athlete;

public class AthleteDAO extends GeneralDAO<Athlete> {

    public void saveAthlete(Athlete athlete) {
        if (athlete.getId() == null) {
            save(athlete);
        } else {
            update(athlete);
        }
    }

    public List<Athlete> getAll() {
        String query = "SELECT a FROM Athlete a WHERE active = true";
        return getList(query);
    }

    public List<Athlete> getBirthdays() {
        int month = LocalDateTime.now().getMonth().getValue();
        String query = "SELECT a FROM Athlete a WHERE active = true AND EXTRACT(MONTH FROM birthdate) = " + month;
        return getList(query);
    }
}

src/main/java/br/com/tkd/spartanos/model/dao/EventDAO.java
package br.com.tkd.spartanos.model.dao;

import java.time.LocalDateTime;
import java.util.List;

import br.com.tkd.spartanos.model.entity.Event;

public class EventDAO extends GeneralDAO<Event> {

    public void saveEvent(Event event) {
        if (event.getId() == null) {
            save(event);
        } else {
            update(event);
        }
    }

    public List<Event> getAll() {
        String query = "SELECT a FROM Event a WHERE active = true";
        return getList(query);
    }

    public List<Event> getMonthlyEvents() {
        int month = LocalDateTime.now().getMonth().getValue();
        String query = "SELECT a FROM Event a WHERE active = true AND EXTRACT(MONTH FROM date) = " + month;
        return getList(query);
    }
}

src/main/java/br/com/tkd/spartanos/model/entity/Athlete.java
package br.com.tkd.spartanos.model.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.temporal.ChronoUnit;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import br.com.tkd.spartanos.model.constants.Gender;
import br.com.tkd.spartanos.model.constants.Graduation;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
@Entity
@Table(name = "`athlete`")
public class Athlete implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;

    @Column(unique = true)
    private String nickname;

    @Enumerated(EnumType.STRING)
    private Graduation graduation;

    private BigDecimal weight;

    private Long height;

    private String phone;

    private String address;

    @Enumerated(EnumType.STRING)
    private Gender gender;

    @Column(name = "emergency_contact")
    private String emergencyContact;

    @Temporal(TemporalType.TIMESTAMP)
    private Date birthDate;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "started_at")
    private Date startedAt;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_at")
    private Date createdAt;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "update_at")
    private Date updatedAt;

    private Boolean active;

    private Boolean coach;

    @PrePersist
    private void onCreate() {
        createdAt = new Date();
        active = true;
    }

    @PreUpdate
    private void oUpdate() {
        updatedAt = new Date();
    }

    public Long getAge() {
        LocalDateTime localDateTime = birthDate.toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDateTime();
        return ChronoUnit.YEARS.between(localDateTime, LocalDateTime.now());
    }


    public String getFormatBirthdate() {
        return new SimpleDateFormat("dd/MM").format(birthDate);
    }

    public void inactivate() {
        active = false;
    }

    public boolean isValid() {
        if (name == null) return false;
        if (nickname == null) return false;
        if (graduation == null) return false;
        if (weight == null) return false;
        if (height == null) return false;
        if (phone == null) return false;
        if (address == null) return false;
        if (gender == null) return false;
        if (emergencyContact == null) return false;
        if (birthDate == null) return false;
        if (startedAt == null) return false;
        return true;
    }

}

src/main/java/br/com/tkd/spartanos/controller/AthleteController.java
package br.com.tkd.spartanos.controller;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;

import org.apache.commons.lang3.StringUtils;

import br.com.tkd.spartanos.model.constants.Gender;
import br.com.tkd.spartanos.model.constants.Graduation;
import br.com.tkd.spartanos.model.dao.AthleteDAO;
import br.com.tkd.spartanos.model.entity.Athlete;
import br.com.tkd.spartanos.util.MessagesUtil;
import lombok.Getter;
import lombok.Setter;

@ManagedBean
public class AthleteController {

    private final AthleteDAO dao = new AthleteDAO();

    @Getter
    @Setter
    private List<Athlete> athleteList = new ArrayList<>();

    @Getter
    @Setter
    private Athlete selectedAthlete = new Athlete();

    @Getter
    @Setter
    private Athlete searchedAthlete = new Athlete();

    @PostConstruct
    public void postConstruct() {
        clearSelectedAthlete();
        clearSearchAthlete();
        updateList();
    }

    public void saveAthlete() {
        if (selectedAthlete.isValid()) {
            dao.saveAthlete(selectedAthlete);
            clearSelectedAthlete();
            updateList();
            MessagesUtil.message("Atleta salvo com sucesso", FacesMessage.SEVERITY_INFO);
        } else {
            MessagesUtil.message("Não foi possível salvar o atleta. Preencha os campos corretamente.",
                    FacesMessage.SEVERITY_ERROR);
        }

    }

    public void deleteAthlete(Athlete athlete) {
        athlete.inactivate();
        dao.update(athlete);
        clearSelectedAthlete();
        updateList();
    }


    public void editAtlete(Athlete athlete) {
        selectedAthlete = athlete;

    }

    public void searchAthlete() {

        boolean hasParam = false;

        if (StringUtils.isNotBlank(searchedAthlete.getName())) {
            hasParam = true;
            athleteList = athleteList.stream().filter(
                    athlete -> athlete.getName().contains(searchedAthlete.getName())).collect
                    (Collectors.toList());
        }

        if (searchedAthlete.getGraduation() != null) {
            hasParam = true;
            athleteList =
                    athleteList.stream().filter(
                            athlete -> athlete.getGraduation().equals(searchedAthlete.getGraduation())).collect(
                            Collectors.toList());
        }

        if (searchedAthlete.getGender() != null) {
            hasParam = true;
            athleteList =
                    athleteList.stream().filter(
                            athlete -> athlete.getGender().equals(searchedAthlete.getGender())).collect(
                            Collectors.toList());
        }

        if(!hasParam) {
            updateList();
        }


    }

    public List<Graduation> getGraduations() {
        return Arrays.asList(Graduation.values());
    }

    public List<Gender> getGenders() {
        return Arrays.asList(Gender.values());
    }

    private void updateList() {
        athleteList = new ArrayList<>();
        athleteList = dao.getAll();
    }

    private void clearSelectedAthlete() {
        selectedAthlete = new Athlete();
    }

    private void clearSearchAthlete() {
        searchedAthlete = new Athlete();
    }

}

src/main/java/br/com/tkd/spartanos/controller/ClassController.java
package br.com.tkd.spartanos.controller;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;

import br.com.tkd.spartanos.model.dao.AthleteDAO;
import br.com.tkd.spartanos.model.entity.Athlete;
import lombok.Getter;
import lombok.Setter;

@ManagedBean
public class ClassController {

    private final AthleteDAO dao = new AthleteDAO();

    @Getter
    @Setter
    private Date date = new Date();

    @Getter
    @Setter
    private List<Athlete> athleteList = new ArrayList<>();

    @PostConstruct
    public void postConstruct() {
        date = new Date();
        updateList();
    }

    private void updateList() {
        athleteList = new ArrayList<>();
        athleteList = dao.getAll();
    }


}

src/main/java/br/com/tkd/spartanos/controller/ErrorController.java
package br.com.tkd.spartanos.controller;

import javax.faces.bean.ManagedBean;

@ManagedBean
public class ErrorController {

    public String returnHome() {
        return "spartanos/home.xhtml?faces-redirect=true";
    }
}

src/main/java/br/com/tkd/spartanos/controller/EventController.java
package br.com.tkd.spartanos.controller;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;

import org.apache.commons.lang3.StringUtils;

import br.com.tkd.spartanos.model.dao.EventDAO;
import br.com.tkd.spartanos.model.entity.Event;
import br.com.tkd.spartanos.util.MessagesUtil;
import lombok.Getter;
import lombok.Setter;

@ManagedBean
public class EventController {

    private final EventDAO dao = new EventDAO();

    @Getter
    @Setter
    private List<Event> eventList = new ArrayList<>();

    @Getter
    @Setter
    private Event selectedEvent = new Event();

    @Getter
    @Setter
    private Event searchedEvent = new Event();

    @PostConstruct
    public void postConstruct() {
        clearSelectedAthlete();
        clearSearchAthlete();
        updateList();
    }

    public void saveEvent() {
        if (selectedEvent.isValid()) {
            dao.saveEvent(selectedEvent);
            clearSelectedAthlete();
            updateList();
            MessagesUtil.message("Evento salvo com sucesso", FacesMessage.SEVERITY_INFO);
        } else {
            MessagesUtil.message("Não foi possível salvar o evento.",
                    FacesMessage.SEVERITY_ERROR);
        }

    }

    public void deleteEvent(Event event) {
        event.inactivate();
        dao.update(event);
        clearSelectedAthlete();
        updateList();
    }


    public void editEvent(Event event) {
        selectedEvent = event;

    }

    public void searchEvent() {

        boolean hasParam = false;

        if (StringUtils.isNotBlank(searchedEvent.getDescription())) {
            hasParam = true;
            eventList = eventList.stream().filter(
                    event -> event.getDescription().contains(searchedEvent.getDescription())).collect
                    (Collectors.toList());
        }

        if (StringUtils.isNotBlank(searchedEvent.getLocation())) {
            hasParam = true;
            eventList =
                    eventList.stream().filter(
                            event -> event.getLocation().equals(searchedEvent.getLocation())).collect(
                            Collectors.toList());
        }

        if(!hasParam) {
            updateList();
        }

    }

    private void updateList() {
        eventList = new ArrayList<>();
        eventList = dao.getAll();
    }

    private void clearSelectedAthlete() {
        selectedEvent = new Event();
    }

    private void clearSearchAthlete() {
        searchedEvent = new Event();
    }

}

src/main/java/br/com/tkd/spartanos/controller/HomeController.java
package br.com.tkd.spartanos.controller;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;

import br.com.tkd.spartanos.model.dao.AthleteDAO;
import br.com.tkd.spartanos.model.dao.EventDAO;
import br.com.tkd.spartanos.model.entity.Athlete;
import br.com.tkd.spartanos.model.entity.Event;
import lombok.Getter;

@ManagedBean
public class HomeController {


    private final AthleteDAO athleteDAO = new AthleteDAO();
    private final EventDAO eventDAO = new EventDAO();

    @Getter
    private List<Athlete> birthdaysList = new ArrayList<>();

    @Getter
    private List<Event> eventList = new ArrayList<>();


    @PostConstruct
    public void postConstruct() {
        birthdaysList = getBirthDays();
        eventList = getEvents();
    }

    private List<Athlete> getBirthDays() {
        return athleteDAO.getBirthdays();

    }

    private List<Event> getEvents() {
        return eventDAO.getMonthlyEvents();
    }

}

src/main/java/br/com/tkd/spartanos/controller/UserController.java
package br.com.tkd.spartanos.controller;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import br.com.tkd.spartanos.model.dao.UserDAO;
import br.com.tkd.spartanos.model.entity.User;
import br.com.tkd.spartanos.util.MessagesUtil;
import lombok.Getter;
import lombok.Setter;

@ManagedBean
@SessionScoped
public class UserController {

    private final UserDAO dao = new UserDAO();

    @Getter
    @Setter
    private String login;

    @Getter
    @Setter
    private String password;

    @Getter
    @Setter
    private User user;

    @Getter
    @Setter
    private User newUser = new User();

    @Getter
    @Setter
    private boolean logged;

    @PostConstruct
    public void postConstruct() {
        newUser = new User();
    }

    public String login() throws Exception {
        User user = dao.login(login, password);
        logged = user != null;
        this.user = user;
        if (!logged) {
            MessagesUtil.message("Usuário e/ou senha incorreto", FacesMessage.SEVERITY_ERROR);
            return "";
        }
        return "spartanos/home.xhtml?faces-redirect=true";
    }


    public void logout() throws Exception {
        logged = false;
        this.user = null;
        //TODO: fix redirect not working
    }

    public String register() {
        dao.saveUser(newUser);
        newUser = new User();
        return "index.xhtml?faces-redirect=true";
    }

    public boolean validateUsername() {
        User user = dao.getByLogin(newUser.getLogin());
        if (user != null) {
            MessagesUtil.message("Login indisponível", FacesMessage.SEVERITY_ERROR);
            return false;
        }
        return true;
    }

}

src/main/webapp/spartanos/athlete.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

<ui:composition template="template.xhtml">

    <ui:define name="content">

        <h:form id="formAthlete">
            <h:graphicImage library="images" name="atlhete.jpg" style="vertical-align: middle; width: 63px; "
                            alt="usuarioIcon"/>
            <p:outputLabel value="Atleta" style="font-size: 250%; vertical-align: middle;"></p:outputLabel>
            <br/>
            <p:separator/>

            <p:messages id="messagesDetails" showDetail="false"/>

            <h:panelGrid columns="4" cellpadding="5" width="100%">


                <p:outputLabel for="nickname" value="Apelido:"/>
                <p:outputLabel for="name" value="Nome:"/>
                <p:outputLabel for="birthdate" value="Data de Nascimento:"/>
                <p:outputLabel for="gender" value="Genêro:"/>

                <p:inputText id="name" value="#{athleteController.selectedAthlete.name}"/>
                <p:inputText id="nickname" value="#{athleteController.selectedAthlete.nickname}"/>
                <p:calendar id="birthdate"
                            pattern="dd/MM/yyyy"
                            value="#{athleteController.selectedAthlete.birthDate}"
                            showOn="button"/>
                <p:selectOneMenu id="gender"
                                 converter="genderConverter"
                                 value="#{athleteController.selectedAthlete.gender}">
                    <f:selectItems value="#{athleteController.genders}" var="item" itemLabel="#{item.description}"
                                   itemValue="#{item}"/>
                </p:selectOneMenu>

                <p:outputLabel for="graduation" value="Graduação:"/>
                <p:outputLabel for="started_at" value="Data de Inscrição:"/>
                <p:outputLabel for="height" value="Altura:"/>
                <p:outputLabel for="weight" value="Peso:"/>

                <p:selectOneMenu id="graduation"
                                 converter="graduationConverter"
                                 value="#{athleteController.selectedAthlete.graduation}">
                    <f:selectItems value="#{athleteController.graduations}" var="item" itemLabel="#{item.description}"
                                   itemValue="#{item}"/>
                </p:selectOneMenu>
                <p:calendar id="started_at"
                            pattern="dd/MM/yyyy"
                            value="#{athleteController.selectedAthlete.startedAt}"
                            showOn="button"/>
                <p:inputNumber id="height" value="#{athleteController.selectedAthlete.height}">
                </p:inputNumber>
                <p:inputNumber id="weight" value="#{athleteController.selectedAthlete.weight}"
                               decimalPlaces="2">
                </p:inputNumber>

                <p:outputLabel for="phone" value="Telefone:"/>
                <p:outputLabel for="address" value="Endereço:"/>
                <p:outputLabel for="emergency_contact" value="Contato em caso de emergência:"/>
                <p:outputLabel for="coach" value="Instrutor:"/>


                <p:inputMask id="phone" value="#{athleteController.selectedAthlete.phone}"
                             mask="(999) 999-9999"/>

                <p:inputText id="address" value="#{athleteController.selectedAthlete.address}"/>

                <p:inputText id="emergency_contact"
                             value="#{athleteController.selectedAthlete.emergencyContact}"/>

                <p:selectBooleanCheckbox id="coach"
                                         value="#{athleteController.selectedAthlete.coach}"/>


                <p:outputLabel for="updated_at" value="Última atualização:"/>
                <p:outputLabel for="created_at" value=""/>
                <p:outputLabel for="id" value=""/>
                <p:outputLabel for="active" value=""/>

                <p:calendar id="updated_at"
                            pattern="dd/MM/yyyy"
                            value="#{athleteController.selectedAthlete.updatedAt}"
                            showOn="none" readonly="true" />
                <h:inputHidden id="created_at" value="#{athleteController.selectedAthlete.createdAt}"> <f:convertDateTime pattern="dd/MM/yyyy"/>  </h:inputHidden>

                <h:inputHidden id="id" value="#{athleteController.selectedAthlete.id}"></h:inputHidden>
                <h:inputHidden id="active" value="#{athleteController.selectedAthlete.active}"></h:inputHidden>
            </h:panelGrid>

            <br/>

            <p:commandButton id="btnSaveAthlete" style="width: 15%;"
                             action="#{athleteController.saveAthlete}" value="Salvar"
                             update="formAthlete"
                             icon="fa fa-save"/>
            <p:separator/>

            <br/>
            <br/>

            <p:outputLabel value="Pesquisar atleta" style="font-size: 150%; vertical-align: middle;"></p:outputLabel>

            <p:panelGrid columns="3" cellpadding="5" width="100%">

                <p:outputLabel for="searchName" value="Nome:"/>
                <p:outputLabel for="searchGraduation" value="Faixa:"/>
                <p:outputLabel for="searchGender" value="Gênero:"/>

                <p:inputText id="searchName" value="#{athleteController.searchedAthlete.name}"/>


                <p:selectOneMenu id="searchGraduation"
                                 converter="graduationConverter"
                                 value="#{athleteController.searchedAthlete.graduation}">
                    <f:selectItem  itemLabel="Selecione a faixa" itemValue="" noSelectionOption="true"/>
                    <f:selectItems value="#{athleteController.graduations}" var="item" itemLabel="#{item.description}"
                                   itemValue="#{item}"/>
                </p:selectOneMenu>
                <p:selectOneMenu id="searchGender"
                                 converter="genderConverter"
                                 value="#{athleteController.searchedAthlete.gender}">
                    <f:selectItem  itemLabel="Selecione o gênero" itemValue="" noSelectionOption="true"/>
                    <f:selectItems value="#{athleteController.genders}" var="item" itemLabel="#{item.description}"
                                   itemValue="#{item}"/>
                </p:selectOneMenu>
            </p:panelGrid>
            <br/>

            <p:commandButton id="btnSearchAthlete" style="width: 15%;"
                             action="#{athleteController.searchAthlete}" value="Pesquisar"
                             update="formAthlete"
                             icon="fa fa-search"/>


            <br/>
            <br/>

            <p:separator/>


            <p:dataTable id="athleteDataTable" var="athlete"
                         value="#{athleteController.athleteList}" paginator="true" rowsPerPageTemplate="5,10,15"
                         emptyMessage="Não foi encontrado nenhum atleta.">

                <p:column headerText="Nome">
                    <h:outputText value="#{athlete.name}">
                    </h:outputText>
                </p:column>

                <p:column headerText="Faixa">
                    <h:outputText value="#{athlete.graduation.description}">
                    </h:outputText>
                </p:column>

                <p:column headerText="Idade">
                    <h:outputText value="#{athlete.age}">
                    </h:outputText>
                </p:column>


                <p:column headerText="Ações">
                    <p:commandButton id="btnUpdateAthlete" style="width: 25%;"
                                     action="#{athleteController.editAtlete(athlete)}" value="Editar"
                                     update="formAthlete"
                                     icon="fa fa-edit"/>

                    <p:commandButton id="btnDeleteAthlete"
                                     action="#{athleteController.deleteAthlete(athlete)}"
                                     value="Excluir"
                                     update="formAthlete"
                                     icon="fa fa-trash-o">



                        <p:confirm header="Confirmação" message="Tem certeza que deseja excluir o atleta?" icon="ui-icon-alert"/>


                        <p:confirmDialog global="true" showEffect="fade" hideEffect="fade">
                            <p:commandButton value="Sim" type="button" styleClass="ui-confirmdialog-yes"
                                             icon="ui-icon-check" />
                            <p:commandButton value="Cancelar" type="button" styleClass="ui-confirmdialog-no"
                                             icon="ui-icon-close" />
                        </p:confirmDialog>

                    </p:commandButton>

                </p:column>


            </p:dataTable>
        </h:form>


    </ui:define>

</ui:composition>
</html>

src/main/webapp/spartanos/class.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html"
>

<ui:composition template="template.xhtml">

    <ui:define name="content">

        <h:form id="formClass">
            <p:panel id="printArea">
            <p:outputLabel value="Lista de presença" style="font-size: 250%; vertical-align: middle;"></p:outputLabel>
            <br/>
            <p:separator/>

            <p:messages id="messagesDetails" showDetail="false"/>

            <h:panelGrid columns="4" cellpadding="5" width="100%">


                <p:outputLabel for="class" value="Aula:"/>

                <p:calendar id="class"
                            pattern="dd/MM/yyyy"
                            showOn="none"
                            readonly="true"
                            value="${classController.date}"/>

            </h:panelGrid>


            <p:separator/>


            <p:dataTable id="athleteDataTable" var="athlete"
                         value="#{classController.athleteList}"
                         emptyMessage="Não foi encontrado nenhum atleta."
                         style="display:block; text-align:center">

                <p:column headerText="Nome">
                    <h:outputText value="#{athlete.name}">
                    </h:outputText>
                </p:column>

                <p:column headerText="Faixa">
                    <h:outputText value="#{athlete.graduation.description}">
                    </h:outputText>
                </p:column>

                <p:column headerText="Idade">
                    <h:outputText value="#{athlete.age}">
                    </h:outputText>
                </p:column>

                <p:column headerText="Presente">
                    <p:selectBooleanButton id="present" onLabel="Sim" offLabel="Não"
                                           style="width:60px" />


                </p:column>


            </p:dataTable>
            </p:panel>

            <br/>

            <p:commandButton id="btnPrintClass" style="width: 15%;"
                             value="Imprimir"
                             icon="fa fa-print">
                <p:printer target="printArea" />
            </p:commandButton>

            <br/>
        </h:form>


    </ui:define>

</ui:composition>
</html>

src/main/webapp/spartanos/home.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

<ui:composition template="template.xhtml">

    <ui:define name="content">
        <h:body>

            Olá, ${userController.user.name}
                <p:dataList id="birthdaysMonth" value="#{homeController.birthdaysList}" var="birthday" type="ordered"
                            emptyMessage="Sem aniversariantes.">
                    <f:facet name="header">
                      Aniversariantes do mês
                    </f:facet>
                    #{birthday.name}, #{birthday.formatBirthdate}, #{birthday.age} anos
                </p:dataList>

                <p:dataList id="events" value="#{homeController.eventList}" var="event" type="ordered"
                            emptyMessage="Sem eventos.">
                    <f:facet name="header">
                        Eventos do mês
                    </f:facet>
                    #{event.description}, [#{event.location}] , #{event.date}
                </p:dataList>

            <br/>
                <p:commandButton id="btnLogout" style="width: 15%;"
                                 action="#{userController.logout}" value="Sair"
                                 icon="fa fa-logout"/>




        </h:body>
    </ui:define>

</ui:composition>
</html>